Update README.md
RoboISM/Roboism pull request #5
Opened 2016-12-23 17:48 UTC by OpenSourceBefikra

2016-12-23 17:56 UTC, markroxor requested changes

2016-12-23 17:56 UTC, markroxor commented on README.md
>    Now, you should see a (myvenv) script before cmd commands. <br>
Dont be so verbose. Remove all the comments after each commamd.

2016-12-23 17:56 UTC, markroxor commented on README.md
> +* Next, check updates (if any) for pip module by
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
> +* After that, do
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
> +* Next, do
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
> +* After that, do
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
>    And
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
>    And
rm

2016-12-23 17:56 UTC, markroxor commented on README.md
>  * Finally, to run a virtual server, do
rm

2016-12-23 18:03 UTC, gitNavV reviewed
Doing

2016-12-24 08:12 UTC, markroxor approved these changes

2016-12-24 08:13 UTC, merged